export const NEW_TASK_ITEM = "MK_NEW_TASK_ITEM";
export const UPDATE_TASK_ITEM = "MK_UPDATE_TASK_ITEM";
export const UPDATE_TASKS = "MK_UPDATE_TASKS";
export const REMOVE_TASK = "MK_REMOVE_TASK";
export const UPDATE_SEARCH_TERM = "MK_UPDATE_SEARCH_TERM";
